# docker-compose.yml (개발용)
version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dupilot-backend
    working_dir: /workspace
    volumes:
      - .:/workspace
      - ./app:/app/app
      - ~/.aws:/root/.aws:ro # host 프로파일을 컨테이너에 전달
      # 실제 있는 구글 API키 위치(json파일) 사용하면 됨
      - ${GOOGLE_APPLICATION_CREDENTIALS_HOST}:${GOOGLE_APPLICATION_CREDENTIALS}:ro # GCP 서비스 키 전달
#     - C:/Users/jjy33/Desktop/jungle/04-namanmu/key:/app/key
    command: sleep infinity
    # command: bash -lc "python script/ingest.py && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    privileged: true
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    restart: unless-stopped
    environment:
      PYTHONPATH: /workspace
      AWS_PROFILE: dev # ← 명시 추천 (s3.py가 기본 dev지만 헷갈림 방지)
      AWS_REGION: ap-northeast-2 # ← 지역 고정
      MONGO_URL_DEV: ${MONGO_URL_DEV}
      UVICORN_HOST: 0.0.0.0
      UVICORN_PORT: 8000      
  mongo:
    image: mongo:7
    container_name: dupilot-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: dupilot

volumes:
  mongo-data:
