# docker-compose.yml (개발용)
version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dupilot-backend
    volumes:
      - .:/workspace
      - ./app:/app/app
      - ~/.aws:/root/.aws:ro    # host 프로파일을 컨테이너에 전달

    command: sleep infinity
    privileged: true
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    restart: unless-stopped
    environment:
      PYTHONPATH: .
      AWS_PROFILE: dev # ← 명시 추천 (s3.py가 기본 dev지만 헷갈림 방지)
      AWS_REGION: ap-northeast-2 # ← 지역 고정
      MONGO_URL_DEV: ${MONGO_URL_DEV}
  mongo:
    image: mongo:7
    container_name: dupilot-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: dupilot

volumes:
  mongo-data:
